Makefiles are terrible

diff --git a/btags b/btags
--- a/btags
+++ b/btags
@@ -1,6 +1,70 @@
 #!/usr/bin/env bash
 
-MAKEFILEDIR=$(cd "$(dirname "$0")"; pwd)
+#Start btags functions
+function btags_check_commands() {
+  FAILED=0
+
+  if [ "$(which "ctags")" = "" ]; then
+    echo "Cannot find 'ctags'. Either the command is not in your PATH, or the command isn't installed. To install 'ctags': sudo apt-get install ctags or similar; see also http://ctags.sourceforge.net."
+    FAILED=1
+  fi
+
+  if [ "$(which "rtags")" = "" ]; then
+    echo "Cannot find 'rtags'. Either the command is not in your PATH, or the command isn't installed. To install 'rtags': gem install bloopletech-rtags; see also https://github.com/bloopletech/rtags."
+    FAILED=1
+  fi
+
+  if [ "$(which "ag")" = "" ]; then
+    echo "Cannot find 'ag'. Either the command is not in your PATH, or the command isn't installed. To install 'ag': Download source from https://github.com/ggreer/the_silver_searcher and then follow the build instructions in the README.md document."
+    FAILED=1
+  fi
+
+  if [ "$FAILED" = "1" ]; then
+    exit 1
+  fi
+}
+
+function btags_clean() {
+  rm -r "$TAGSDIR"/*
+}
+
+function btags_generate() {
+  cd "$SRCDIR"
+
+  ag --search-files --nocolor -g '^(.*\.build\.xml|.*\.asm|.*\.ASM|.*\.s|.*\.S|.*\.A51|.*\.29k|.*\.29K|.*\.66k|.*\.66K|.*\.66s|.*\.66S|.*\.66x|.*\.66X|.*\.68k|.*\.68K|.*\.68s|.*\.68S|.*\.68x|.*\.68X|.*\.86k|.*\.86K|.*\.86s|.*\.86S|.*\.86x|.*\.86X|.*\.88k|.*\.88K|.*\.88s|.*\.88S|.*\.88x|.*\.88X|.*\.x66|.*\.x68|.*\.x86|.*\.x88|.*\.X66|.*\.X68|.*\.X86|.*\.X88|.*\.asp|.*\.asa|.*\.awk|.*\.gawk|.*\.mawk|.*\.bas|.*\.bi|.*\.bb|.*\.pb|.*\.bet|.*\.c|.*\.cc|.*\.cp|.*\.cpp|.*\.cxx|.*\.h|.*\.hh|.*\.hp|.*\.hpp|.*\.hxx|.*\.C|.*\.H|.*\.cs|.*\.cbl|.*\.cob|.*\.CBL|.*\.COB|.*\.bat|.*\.cmd|.*\.e|.*\.erl|.*\.ERL|.*\.hrl|.*\.HRL|.*\.as|.*\.mxml|.*\.f|.*\.for|.*\.ftn|.*\.f77|.*\.f90|.*\.f95|.*\.F|.*\.FOR|.*\.FTN|.*\.F77|.*\.F90|.*\.F95|.*\.go|.*\.htm|.*\.html|.*\.java|.*\.js|.*\.cl|.*\.clisp|.*\.el|.*\.l|.*\.lisp|.*\.lsp|.*\.lua|.*\.mak|.*\.mk|Makefile|makefile|GNUmakefile|.*\.m|.*\.ml|.*\.mli|.*\.p|.*\.pas|.*\.pl|.*\.pm|.*\.plx|.*\.perl|.*\.php|.*\.php3|.*\.phtml|.*\.py|.*\.pyx|.*\.pxd|.*\.pxi|.*\.scons|.*\.rexx|.*\.rx|.*\.ruby|.*\.SCM|.*\.SM|.*\.sch|.*\.scheme|.*\.scm|.*\.sm|.*\.sh|.*\.SH|.*\.bsh|.*\.bash|.*\.ksh|.*\.zsh|.*\.sl|.*\.sml|.*\.sig|.*\.sql|.*\.tcl|.*\.tk|.*\.wish|.*\.itcl|.*\.tex|.*\.vr|.*\.vri|.*\.vrh|.*\.v|.*\.vhdl|.*\.vhd|.*\.vim|.*\.y)$' > "$TAGSDIR/ctags.files"
+  while read file; do
+    if [ "$file" -nt "$TAGSDIR/$file.tags" ]; then
+      echo "$file"
+    fi
+  done < "$TAGSDIR/ctags.files" > "$TAGSDIR/ctags.changed.files"
+
+  ag --search-files --nocolor -g '^(.*\.rb|.*\.rake|.*\.ru|Gemfile|Guardfile|Procfile|Rakefile)$' > "$TAGSDIR/rtags.files"
+  while read file; do
+    if [ "$file" -nt "$TAGSDIR/$file.tags" ]; then
+      echo "$file"
+    fi
+  done < "$TAGSDIR/rtags.files" > "$TAGSDIR/rtags.changed.files"
+
+  if [ ! -s "$TAGSDIR/ctags.changed.files" -a ! -s "$TAGSDIR/rtags.changed.files" ]; then
+    return 0
+  fi
+
+  parallel mkdir -p "$TAGSDIR"/{//} "&&" "ctags -xu" {} ">" "$TAGSDIR"/{}.tags "2>/dev/null" "&&" echo -n "." < "$TAGSDIR/ctags.changed.files"
+
+  parallel mkdir -p "$TAGSDIR"/{//} "&&" "rtags -x -B" {} ">" "$TAGSDIR"/{}.tags "2>/dev/null" "&&" echo -n "." < "$TAGSDIR/rtags.changed.files"
+
+  cat "$TAGSDIR"/{ctags,rtags}.files | sed 's/^.*$/& path 1 & path/g' > "$TAGSDIR/files.tags"
+
+  while read file; do
+    cat "$TAGSDIR/$file.tags"
+  done < <(cat "$TAGSDIR"/{ctags,rtags}.files) > "$TAGSDIR/tags.tags"
+
+  cat "$TAGSDIR/files.tags" >> "$TAGSDIR/tags.tags"
+
+  rm "$TAGSDIR"/{ctags,rtags}.files "$TAGSDIR"/{ctags,rtags}.changed.files
+}
+
+#End btags functions
 
 case "$1" in
   path) ACTION="path";;
@@ -17,7 +81,6 @@ esac
 
 SRCDIR=$(realpath "$PWD")
 TAGSDIR="$HOME/.btags$SRCDIR"
-PATH="$PATH:$MAKEFILEDIR"
 OVERALLTAGSFILEPATH="$TAGSDIR/tags.tags"
 
 if [[ "$ACTION" == "btags" || "$ACTION" == "debug" || "$ACTION" == "path" || "$ACTION" == "stats" ]]; then
@@ -40,24 +103,25 @@ cd "$TAGSDIR"
   flock -n 9 || { echo "An instance of btags is already updating this project."; exit 1; }
 
   if [[ "$ACTION" == "btags" ]]; then
-    make -j -r -s -f "$MAKEFILEDIR/Makefile" srcdir="$SRCDIR" check_commands 2>/dev/null
-    make -j -r -s -f "$MAKEFILEDIR/Makefile" srcdir="$SRCDIR" 2>/dev/null
+    btags_check_commands
+    btags_generate
 
     echo ""
     echo "$TAGSFILEPATH"
   elif [[ "$ACTION" == "debug" ]]; then
     echo "Starting in $PWD"
     echo "Srcdir is $SRCDIR"
-    echo "Running make..."
-    make -j -r -d -f "$MAKEFILEDIR/Makefile" srcdir="$SRCDIR" check_commands
-    make -j -r -d -f "$MAKEFILEDIR/Makefile" srcdir="$SRCDIR"
+    echo "Checking commands..."
+    btags_check_commands
+    echo "Generating updates..."
+    btags_generate
 
     echo ""
-    echo "Make finished"
+    echo "Generating updates finished"
     echo "Tags file path:"
     echo "$TAGSFILEPATH"
   elif [[ "$ACTION" == "clean" ]]; then
-    make -j -r -s -f "$MAKEFILEDIR/Makefile" srcdir="$SRCDIR" clean 2>/dev/null
+    btags_clean
     echo ""
   elif [[ "$ACTION" == "path" ]]; then
     if ! [ -e "$TAGSFILEPATH" ]; then
